name: Woot
favicon: null
layout_spectrum: 0.5614478690549731
typography_spectrum: 0.16309036640450358
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d4d5da'
    - '#a7a5a6'
    - '#5f6c63'
    - '#09101a'
    - '#8d0929'
  brandStrength: 0.5939236199483275
  lightness: 0.3836462586186826
  saturation: 0.12904228107072413
  rhythmicContrast: 0.4861677868757397
purpose: []
