name: Woot
favicon: null
layout_spectrum: 1
typography_spectrum: 0.74297
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#4a3125'
    - '#dcd6d6'
    - '#898471'
    - '#70041a'
  brandStrength: 0
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
