name: Woot
favicon: null
layout_spectrum: 1
typography_spectrum: 0.74297
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#630e1e'
    - '#f9fdef'
    - '#fcaad0'
    - '#3c6918'
    - '#7ab632'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
