name: Woot
favicon: null
layout_spectrum: 1
typography_spectrum: 0.74297
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f0f3f8'
    - '#044205'
    - '#75a61e'
    - '#498a16'
    - '#abc086'
  brandStrength: 1
  lightness: 0.4375
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
