name: Woot
favicon: null
layout_spectrum: 1
typography_spectrum: 0.74297
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#181e1a'
    - '#547813'
    - '#fffeff'
    - '#af94a2'
    - '#dbd0d6'
  brandStrength: 0
  lightness: 0.4375
  saturation: 0.25
  rhythmicContrast: 0
purpose: []
